### ISSUE TITLE
Utiliser date du jour, date du lendemain, ou autre

### ISSUE THREAD

**Issue by Showiengum** [cerberustesting/cerberus-robot-extension#12]
Bonjour,

je souhaiterais insérer dans une action une date (récupérée comme celle du jour ou calculée comme celle du ledemain). Saisie dans un champ par exemple mais en client lourd.

Est-ce possible ?

**Comment by bcivel** [comment]
Bonjour,

Tu peux utiliser une propriété de type text, qui contiendrait : %system.TODAY-yyyy%/%system.TODAY-MM%/%system.TODAY-dd%

Ca marche aussi avec %system.TOMORROW-yyyy%/%system.TOMORROW-MM%/%system.TOMORROW-dd%

<img width="1149" alt="Capture d’écran 2021-03-17 à 17 20 24" src="https://user-images.githubusercontent.com/5376184/111501216-1208ec80-8745-11eb-9dfd-c01c1bbbcb93.png">

A dispo

**Comment by Showiengum** [comment]
Merci @bcivel
