### ISSUE TITLE
Fonctionnement du type

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-robot-extension#3]
Salut Benoit,

As-tu tester le 'type' avec sikuli ?

Les clicks s'enchaine bien mais avec le type j'ai : 

![image](https://cloud.githubusercontent.com/assets/995694/20713815/07418fb2-b64a-11e6-917a-f5e6494db837.png)

Merci

**Comment by bcivel** [comment]
Hello Victorien,
Oui, je l'ai déjà utilisé. As-tu la stack de selenium pour m'aider à comprendre?
As tu vu que la souris se déplaçais bien au dessus du champ avant de planter?
Merci

**Comment by vitoo** [comment]
Hello Benoit,

1ere erreur de ma part, j'ai mis dans le nom de l'application object un point  " 2.1_bt" ça provoque l'erreur du screen

2eme problème : 

Le screenshot que j'upload dans ApplicationObject est resize, provoquant un 'element not found' : 

Cette image : 
![image](https://cloud.githubusercontent.com/assets/995694/20746714/334ad544-b6e7-11e6-9cca-8b6b94f82cb2.png)

Deviens sur le poste avec le node sikuli  : 
![image](https://cloud.githubusercontent.com/assets/995694/20746702/2b12107c-b6e7-11e6-89bc-6ecd141ccb5a.png)

**Comment by bcivel** [comment]
Effectivement, j'ai corrigé le problème du retaillage d'image. Je push tout à l'heure.
Je vois également le problème du point dans le nom de property.
Merci pour ton aide

**Comment by vitoo** [comment]
Hello @bcivel 

tu peux push ?

**Comment by bcivel** [comment]
C'est fait.
