### ISSUE TITLE
Paramètre cerberus_sikuli_minSimilarity ne semble pas fonctionner

### ISSUE THREAD

**Issue by Showiengum** [cerberustesting/cerberus-robot-extension#9]
Bonjour,

je viens de passer le paramètre **cerberus_sikuli_minSimilarity** à **1**, n'arrivant pas à faire différencier à Cerberus une case cochée d'une case décochée.

Quelqu'un pourrait-il me confirmer si celà fonctionne ou pas ?

Dans mon cas si je cherche à décocher des cases, si plus aucune case n'est cochée, Cerberus coche une case vide.

Voilà les **Application Objects** pour les cases Cochée / Décochée :

![CaseCochee_Chk](https://user-images.githubusercontent.com/51801407/103551608-db903500-4eaa-11eb-8351-40f304641cc3.png)
![CaseDecochee_Chk](https://user-images.githubusercontent.com/51801407/103551610-dc28cb80-4eaa-11eb-921e-1d519fa20e8d.png)

**Comment by Showiengum** [comment]
Suite à la mise à jour de Cerberus je n'avais pas fait la mise à jour de l'extension pour Sikuli.
Je confirme que le réglage du paramètre fonctionne.

**Comment by vertigo17** [comment]
Good ;-)
